# Generated by Django 4.1 on 2022-08-05 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('Movie_Rank', models.AutoField(primary_key=True, serialize=False)),
                ('Movie_Name', models.CharField(max_length=200)),
                ('Year_of_Release', models.IntegerField()),
                ('Movie_Rating', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Movie_Duration', models.DurationField()),
                ('Movie_Description', models.CharField(max_length=1000)),
                ('Date_Time', models.DateTimeField()),
            ],
        ),
    ]
